-- DEPRECATED — this file can be deleted.
--
-- The schema for the Zimbabwe Information Platform now lives entirely in the
-- shared mukoko_platform_cloud Supabase project (ID: tdcpuzqyoodrdsxldgsh).
--
-- Schemas: places, hospitality, commerce, identity, business, content,
--          engagement, system, news
--
-- This repo (zti-docs) does NOT own any database schema. It is a read-only
-- consumer of the unified platform database via Supabase publishable key + RLS.
--
-- To remove this file: git rm supabase/schema.sql
